config/routes.rb
StoryTime::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
	
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :stories do
    get 'graph'
    resources :pages do 
      resources :links
    end
    resources :normal_pages, :controller => 'pages'
    resources :end_pages, :controller => 'pages'
    resources :win_pages, :controller => 'pages'
    resources :start_pages, :controller => 'pages'
    resources :ratings
  end
  match '/stories/:story_id#:id', to: 'story#show', :via => [:get], as: 'present_story_page'
  
  match '/reports/activity', to: 'reports#recent_activity', :via => [:get]


  root to: 'stories#index'
	
	match '/', to: 'stories#index', :via => [:get]
  match '/help',    to: 'static_pages#help', :via => [:get]
  match '/about',   to: 'static_pages#about', :via => [:get]
  match '/contact', to: 'static_pages#contact', :via => [:get]

	match '/signup',  to: 'users#new', :via => [:get]
  match '/signin',  to: 'sessions#new', :via => [:get]
  match '/signout', to: 'sessions#destroy', :via => [:delete]
	
	











end

app/models/rating.rb
class Rating < ActiveRecord::Base
  
  belongs_to :story
  belongs_to :user
  validates_length_of :comment, :maximum => 2000
  
  def subject_user
  	story.user
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  
  # GET /ratings
  # GET /ratings.json
  def index
    @story = Story.find(params[:story_id])
    @ratings = @story.ratings

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @story = Story.find(params[:story_id])
    @rating = @story.ratings.build

    respond_to do |format|
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @story = Story.find(params[:story_id])
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(params[:rating])
    
    @rating.story_id = params[:story_id] if(@rating.story.nil?)
    
    if(old_rating = @rating.story.user_rating(current_user))
      old_rating.update_attributes(params[:rating])
      @rating = old_rating
    end
    
    respond_to do |format|
      if @rating.save
        format.json { render json: @rating, status: :created, location: nil }
        format.html { render partial: 'rating' }
      else
        format.json { render json: @rating.errors, status: :unprocessable_entity }
        format.html { render partial: 'rating' }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.json { render json: @rating, status: :ok, location: nil }
      else
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_rating.html.erb
<%= form_for([@story, rating], :remote => true, :html => { :class => "rating" }) do |f| %>
  <div class="field">
    <div class="rating">
      <input type="radio" id="star5" name="rating[score]" value="5" <%= rating.score == 5 ? "checked" : "" %> /><label for="star5" title="Rocks!"></label>
      <input type="radio" id="star4" name="rating[score]" value="4" <%= rating.score == 4 ? "checked" : "" %> /><label for="star4" title="Pretty good really"></label>
      <input type="radio" id="star3" name="rating[score]" value="3" <%= rating.score == 3 ? "checked" : "" %> /><label for="star3" title="Ok, I guess"></label>
      <input type="radio" id="star2" name="rating[score]" value="2" <%= rating.score == 2 ? "checked" : "" %> /><label for="star2" title="Kinda bad"></label>
      <input type="radio" id="star1" name="rating[score]" value="1" <%= rating.score == 1 ? "checked" : "" %> /><label for="star1" title="'Needs improvement'"></label>
    </div>
  </div>
  <div>
    <%= f.text_area :comment, placeholder: "Comments", rows: 3%>
    <%= f.hidden_field :user_id %> 
    <%= f.hidden_field :story_id %>
  </div>
  <%= f.submit "Rate", class: "btn-square btn-orange btn-square-small ratingSubmit" %>
   <div id="ratingSuccess" class="alert alert-success ratingAlert">Saved!</div>
   <div id="ratingError" class="alert alert-error ratingAlert">Uh.. some sort of problem happen</div>
  <script>
  $(document).ready(function() {
    $("div.ratingAlert").hide();
    $("form.rating").bind('ajax:success', function() { flash($("#ratingSuccess")); } );
    $("form.rating").bind('ajax:error', function() { flash($("#ratingError")); } );
 
  });</script>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Story</th>
    <th>Score</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.user_id %></td>
    <td><%= rating.story_id %></td>
    <td><%= rating.score %></td>
    <td><%= rating.comment %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>
<%= render partial: '/ratings/form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>

<p>
  <b>Story:</b>
  <%= @rating.story_id %>
</p>

<p>
  <b>Score:</b>
  <%= @rating.score %>
</p>

<p>
  <b>Comment:</b>
  <%= @rating.comment %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>