config/routes.rb
StoryTime::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
	
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :stories do
    get 'graph'
    resources :pages do 
      resources :links
    end
    resources :normal_pages, :controller => 'pages'
    resources :end_pages, :controller => 'pages'
    resources :win_pages, :controller => 'pages'
    resources :start_pages, :controller => 'pages'
    resources :ratings
  end
  match '/stories/:story_id#:id', to: 'story#show', :via => [:get], as: 'present_story_page'
  
  match '/reports/activity', to: 'reports#recent_activity', :via => [:get]


  root to: 'stories#index'
	
	match '/', to: 'stories#index', :via => [:get]
  match '/help',    to: 'static_pages#help', :via => [:get]
  match '/about',   to: 'static_pages#about', :via => [:get]
  match '/contact', to: 'static_pages#contact', :via => [:get]

	match '/signup',  to: 'users#new', :via => [:get]
  match '/signin',  to: 'sessions#new', :via => [:get]
  match '/signout', to: 'sessions#destroy', :via => [:delete]
	
	











end

app/models/story.rb
# https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md
require "core_ext/array.rb"
class Story < ActiveRecord::Base
  include StoriesHelper
  
  
  has_many :pages
  has_many :ratings
  has_many :games
  has_many :players, through: :games
  belongs_to :user
  has_one_attached :image
  validates :image, file_content_type: {
    allow: ["image/jpeg", "image/png"],
    if: -> { image.attached? },
  }
  after_initialize :init
  
  
  DRAFT     = 0
  PUBLISHED = 1
  REVIEW    = 2

  STATUSES = {
    DRAFT    => 'Draft',
    PUBLISHED    => 'Published',
    REVIEW => 'Review'
  }

  validates_inclusion_of :status, :in => STATUSES.keys,
      :message => "{{value}} must be in #{STATUSES.values.join ','}"

  def init
    self.status = 0 if self.status.nil?
  end

  def self.sort_by_score(stories)
    
    stories.sort_by { |s|  s.decayed_weighted_score }.reverse

  end

  def decayed_weighted_score
    return 0 if ratings.select{|r| !r.score.nil?}.empty?
    latest = ratings.last.created_at
    return decay_rating(weighted_average_rating, latest)
  end

  def decay_rating(rating, time)
    decay = Math.exp((time.to_datetime - DateTime.now).to_i/40.0)
    return rating/2.0 + (rating-rating/2.0)*decay
  end

  def weighted_average_rating
    get_average_rating * ((ratings.count*4.0)**(1.0/3.0))
  end

  def rating_deviation
    avg = get_average_rating 
    return Math.sqrt(ratings.select {|r| !r.score.nil? }.collect{ |r| (r.score - avg)**2 }.mean||0)
  end

  # just a helper method for the view
  def status_name
    STATUSES[status]
  end
  
  def user_rating(user)
    self.ratings.find_by_user_id(user.id) || self.ratings.build(user_id: user.id)
  end
  
  def get_word_count
    self.pages.collect { |p| p.word_count }.sum
  end
  
  def get_player_count
    self.games.count
  end
  
  def get_winner_count
    
    self.games.where(["wins = 1"]).count
  end

  def get_fail_count
    self.games.sum(:fails)
  end
  
  def first_page
    p = self.pages.where(["type='StartPage'"]).first
    if(p.nil?)
      p = self.pages.order("id").first
    end
    return p
  end
  
  def get_average_rating
    self.ratings.average(:score)
  end
  
  def get_median_rating
    median(self.ratings.select { |r| !r.score.nil? }.collect { |r| r.score })
  end
  
  def get_comment_ratings
    self.ratings.select { |r| !r.comment.blank? }
  end

  def image_safe(size=nil)
    image.file? ? image.url((size.nil? || size > 200) ? :large : :medium) : (image_url.blank? ? "/assets/placeholder.png" : image_url)
  end
  
  def get_game_for_user(user)
    return ((game = self.games.find_by_user_id(user.id)) ? game : self.games.create!(user_id: user.id, wins: 0, fails: 0, pages: 0))
  end
end

app/controllers/stories_controller.rb
require 'will_paginate/array'
require 'core_ext/array'

class StoriesController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :new, :create, :graph, :destroy]
  before_action :correct_user,   only: [:destroy, :edit, :update]
  
  def stories_params
    params.permit(:sort,:page,:id,:story_id,:story)
  end

  def index
    @stories = Story.where(
      signed_in? ? 
        (current_user.admin?) ? {} : ["status = 1 or user_id = ?", current_user.id]
      :
        ["status = 1"]
    )
    stories_params[:sort] = "rating" if(!["rating","title","date"].include? (stories_params[:sort]||"").downcase)

    case stories_params[:sort]
      when "rating"
        @stories = Story.sort_by_score(@stories)
      when "title"
        @stories = @stories.sort_by &:title
      when "date"
        @stories = @stories.sort_by(&:created_at).reverse
    end
    @stories = @stories.paginate(page: stories_params[:page], per_page: 10)
    @activity = Micropost.get_recent(10)
  end 
  
  def show
    @story = Story.find(stories_params[:id])
  end
  
  def edit
    @story = Story.find(stories_params[:id])
  end
  
  def graph
    @story = Story.find(stories_params[:story_id])
  end
  
  def new
    @story = current_user.stories.build
  end
  
  def create
    @story = current_user.stories.build(stories_params[:story])
    if @story.save
      flash[:success] = "Cool you created a story. Now add some pages."
      redirect_to edit_story_path(@story)
    else
      render 'new'
    end
  end
  
  def update
    @story = Story.find(stories_params[:id])
    if(@story.status != Story::PUBLISHED and !stories_params[:story][:status].nil? and stories_params[:story][:status].to_i == Story::PUBLISHED)
      current_user.microposts.create({content: "#{current_user.name} just published a new story, <a href='#{story_path(@story)}'>'#{@story.title}'</a>" })
    end
    if @story.update_attributes(stories_params[:story])
      flash[:success] = "Story updated"
    end
    redirect_to edit_story_path(@story)
  end
   
  def destroy
    @story = Story.find(stories_params[:id])
    @story.destroy
    flash[:success] = "Story destroyed."
    redirect_to stories_url
  end
  
  private

    def correct_user
      @story = current_user.stories.find_by_id(stories_params[:id])
      if(@story.nil? and !current_user.admin?)
        flash[:error] = "You need to be the owner of that story to modify it."
        redirect_to root_url if @story.nil?
      end
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
  include SessionsHelper
  
  def user_can_edit(story)
    return (!current_user.nil? && story.user_id == current_user.id) || current_user.admin?
  end
  
  def median(array)
    return nil if array.empty?
    array.select {|v| !v.nil? }.sort!
    middle = array.length / 2
    (array.length % 2 == 1) ? array[middle] : ((array[middle-1] + array[middle])/2)
  end
 
  def image_for_story(story, size=nil, class_name=nil)
    image_url = story.image_safe(size)
    image_tag(image_url, alt: story.title, width: size, class: class_name||"image")
  end
  
  def get_story_title(story)
    if(story.title.empty?)
      return raw '<span class="disabled">Unnamed Story</span>'
    else
      return story.title
    end
  end
end

app/views/stories/_audio.html.erb
<script src="http://connect.soundcloud.com/sdk.js"></script>
<script>
SC.initialize({
  client_id: "1a0be4cf7910f12cad37af2cd63e7ed0"
});
</script>

app/views/stories/_fields.html.erb
<%= render "shared/error_messages", object: f.object %>
      
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :description %>
<%= f.text_field :description %>
<div class="well">
<%= image_for_story @story %>
<%= f.label :image %>
<%= f.file_field :image %>
 <br/>- or -
<%= f.label :image_url %>
<%= f.text_field :image_url,  placeholder: "URL to your image"%>
</div>

app/views/stories/_graph.html.erb
<div id="infovis" class="unselectable"></div>
<div id="log" style="display:none"></div>
<script>
var labelType, useGradients, nativeTextSupport, animate;

(function() {
  var ua = navigator.userAgent,
      iStuff = ua.match(/iPhone/i) || ua.match(/iPad/i),
      typeOfCanvas = typeof HTMLCanvasElement,
      nativeCanvasSupport = (typeOfCanvas == 'object' || typeOfCanvas == 'function'),
      textSupport = nativeCanvasSupport 
        && (typeof document.createElement('canvas').getContext('2d').fillText == 'function');
  //I'm setting this based on the fact that ExCanvas provides text support for IE
  //and that as of today iPhone/iPad current text support is lame
  labelType = (!nativeCanvasSupport || (textSupport && !iStuff))? 'Native' : 'HTML';
  nativeTextSupport = labelType == 'Native';
  useGradients = nativeCanvasSupport;
  animate = !(iStuff || !nativeCanvasSupport);
})();

var Log = {
  elem: false,
  write: function(text){
    if (!this.elem) 
      this.elem = document.getElementById('log');
    this.elem.innerHTML = text;
    this.elem.style.left = (500 - this.elem.offsetWidth / 2) + 'px';
  }
};

// init data
var json = [
  <% @story.pages.each do |page| 
    links = page.links.select {|l| l.page_id == page.id}
  %>
  { "adjacencies" : [ 
    <% links.each do |link| %>
      {
        "nodeTo": "<%= "page#{link.other_page_id}" %>",
        "nodeFrom": "<%= "page#{page.id}"%>",
        "data": {}
      }<%= (link == links.last ? "" : ",") %>
    <% end %>
    ], 
    "data": {
      "$color": "<%= page.is_a?(StartPage) ? "#00CF00" : page.is_a?(WinPage) ? "#006ECC" : page.is_a?(EndPage) ? "#F06060" : "#F9A834" %>", 
      "$type": "<%= page.is_a?(StartPage) ? "triangle" : page.is_a?(EndPage) ? "square" : "circle" %>"
    }, 
    "id": "<%= "page#{page.id}"%>", 
    "name": "<%= "#{page.title}"%>"
  }<%= (page == @story.pages.last ? " " : ",") %>
  <% end %>
];

function init(){  
  // init ForceDirected
  var fd = new $jit.ForceDirected({
    //id of the visualization container
    injectInto: 'infovis',
    
    //Enable zooming and panning
    //with scrolling and DnD
    Navigation: {
      enable: true,
      type: 'Native',
      //Enable panning events only if we're dragging the empty
      //canvas (and not a node).
      panning: 'avoid nodes',
      zooming: 10 //zoom speed. higher is more sensible
    },
    
    // Change node and edge styles such as
    // color and width.
    // These properties are also set per node
    // with dollar prefixed data-properties in the
    // JSON structure.
    Node: {
      overridable: true,
      dim: 7
    },
    Edge: {
      overridable: true,
      color: '#23A4FF',
      lineWidth: 0.4
    },
    // Add node events
    Events: {
      enable: true,
      type: 'Native',
      //Change cursor style when hovering a node
      onMouseEnter: function() {
        fd.canvas.getElement().style.cursor = 'move';
      },
      onMouseLeave: function() {
        fd.canvas.getElement().style.cursor = '';
      },
      //Update node positions when dragged
      onDragMove: function(node, eventInfo, e) {
        var pos = eventInfo.getPos();
        node.pos.setc(pos.x, pos.y);
        fd.plot();
      },
      //Implement the same handler for touchscreens
      onTouchMove: function(node, eventInfo, e) {
        $jit.util.event.stop(e); //stop default touchmove event
        this.onDragMove(node, eventInfo, e);
      }
    },
    //Number of iterations for the FD algorithm
    iterations: 200,
    //Edge length
    levelDistance: 70,
    // This method is only triggered
    // on label creation and only for DOM labels (not native canvas ones).
    onCreateLabel: function(domElement, node){
      // Create a 'name' and 'close' buttons and add them
      // to the main node label
      var nameContainer = document.createElement('span'),
          closeButton = document.createElement('span'),
          style = nameContainer.style;
      nameContainer.className = 'nodeName';
      nameContainer.innerHTML = node.name;
      closeButton.className = 'nodeClose';
      closeButton.innerHTML = 'x';
      domElement.appendChild(nameContainer);
      //domElement.appendChild(closeButton);
      style.fontSize = "0.8em";
      style.color = "#666";
      //Fade the node and its connections when
      //clicking the close button
      closeButton.onclick = function() {
        node.setData('alpha', 0, 'end');
        node.eachAdjacency(function(adj) {
          adj.setData('alpha', 0, 'end');
        });
        fd.fx.animate({
          modes: ['node-property:alpha',
                  'edge-property:alpha'],
          duration: 500
        });
      };
      //Toggle a node selection when clicking
      //its name. This is done by animating some
      //node styles like its dimension and the color
      //and lineWidth of its adjacencies.
      nameContainer.onclick = function() {
        //set final styles
        fd.graph.eachNode(function(n) {
          if(n.id != node.id) delete n.selected;
          n.setData('dim', 7, 'end');
          n.eachAdjacency(function(adj) {
            adj.setDataset('end', {
              lineWidth: 0.4,
              color: '#23a4ff'
            });
          });
        });
        if(!node.selected) {
          node.selected = true;
          node.setData('dim', 17, 'end');
          node.eachAdjacency(function(adj) {
            adj.setDataset('end', {
              lineWidth: 3,
              color: '#36acfb'
            });
          });
        } else {
          //make it scroll to the page you've clicked on
          //delete node.selected;
          var divId = node.id.replace(/^page/g,"#divPage");
          $.scrollTo($(divId), 800, {offset: -50});
          highlight(divId);
        }
        //trigger animation to final styles
        fd.fx.animate({
          modes: ['node-property:dim',
                  'edge-property:lineWidth:color'],
          duration: 500
        });
        // Build the right column relations list.
        // This is done by traversing the clicked node connections.
        var html = "<h4>" + node.name + "</h4><b> connections:</b><ul><li>",
            list = [];
        node.eachAdjacency(function(adj){
          if(adj.getData('alpha')) list.push(adj.nodeTo.name);
        });
        //append connections information
        $jit.id('inner-details').innerHTML = html + list.join("</li><li>") + "</li></ul>";
        
        
        
      };
    },
    // Change node styles when DOM labels are placed
    // or moved.
    onPlaceLabel: function(domElement, node){
      
      var style = domElement.style;
      var left = parseInt(style.left);
      var top = parseInt(style.top);
      var w = domElement.offsetWidth;
      style.left = (left - w / 2) + 'px';
      style.top = (top + 10) + 'px';
      style.display = '';
    }
  });
  // load JSON data.
  fd.loadJSON(json);
  // compute positions incrementally and animate.
  fd.computeIncremental({
    iter: 40,
    property: 'end',
    onStep: function(perc){
      Log.write(perc + '% loaded...');
    },
    onComplete: function(){
      Log.write('done');
      fd.animate({
        modes: ['linear'],
        transition: $jit.Trans.Elastic.easeOut,
        duration: 2500
      });
    }
  });
  // end
}

$(document).ready(function() { init(); });
</script>

app/views/stories/_info.html.erb
<div class="tabbable tabs-below">
  <div class="tab-content">
    <div class="tab-pane active" id="tab-stats<%= story.id %>">
      <ul class="thumbnails">
        <li><a href="#" rel="tooltip" data-original-title="Pages" class="atooltip"><i class="fa fa-file"></i> <%= story.pages.count %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Words" class="atooltip"><i class="fa fa-file-o" alt="words"></i> <%= story.get_word_count %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Plays" class="atooltip"><i class="fa fa-group" alt="plays"></i> <%= story.get_player_count %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Won" class="atooltip"><i class="fa fa-trophy" alt="won"></i> <%= story.get_winner_count %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Median rating" class="atooltip"><i class="fa fa-star" alt="med_rating">
        </i> 
          <%= number_with_precision story.get_median_rating, precision: 1 %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Standard deviation" class="atooltip"><i class="fa fa-bar-chart-o" alt="standard_deviation"></i> 
          <%= number_with_precision story.rating_deviation, precision: 1 %></a>
        </li>
        <li><a href="#" rel="tooltip" data-original-title="Popularity" class="atooltip"><i class="fa fa-fire" alt="popularity"></i> 
          <%= number_with_precision story.decayed_weighted_score, precision: 1 %></a>
        </li>
      </ul>
      </div>
    <div class="tab-pane" id="tab-comments<%= story.id %>">
      <% if story.get_comment_ratings.count > 0 %>
        <% story.get_comment_ratings.each do |r| %>
          <blockquote>
            <p><%= r.comment %> </p>
            <small><%= r.user.name %></small>
          </blockquote>
        <% end %>
      <% else %>
        <div class="no_content">No comments yet</div>
      <% end %>
    </div>
  </div>
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab-stats<%= story.id %>" data-toggle="tab"><i class="fa fa-cogs"></i> Stats</a></li>
    <li><a href="#tab-comments<%= story.id %>" data-toggle="tab"><i class="fa fa-comments"></i> Comments</a></li>
  </ul>
</div>

app/views/stories/_story.html.erb
<li class="card story_card">

  <div class="story_box_left span2">
    <div class="story_thumb">
      <%= image_for_story story, 100 %>
    </div>
    <div class="story_button">
      <%= link_to story_path(story) do %><div class="btn-round btn-green"><i class='fa fa-play fa fa-large'></i></div><% end %>
      <% if signed_in? and user_can_edit(story) %>
        <%= link_to edit_story_path(story) do %><div class="btn-round btn-yellow btn-round-small"><i class='fa fa-edit'></i></div><% end %>
      <% end %>
      <% if signed_in? and current_user.admin? %>
        <%= link_to story_path(story), method: :delete do %><div class="btn-round btn-red btn-round-small"><i class='fa fa-trash-o'></i></div><% end %>
      <% end %>
    </div>
  </div>
  <div class="story_right <%= !(hideAuthor||=nil).nil? ? "span6" : "span7" %>">
    <% if((hideAuthor||=nil).nil?) %>
      <%=link_to story.user do %>
        <%= render partial: "/users/avatar", locals: { user: story.user, size: 52 } %>
      <% end %>
    <% end %>
    <h3><%= get_story_title(story) %></h3>
    <small><cite>By <%= story.user.nil? ? "Anonymous" : story.user.name %></cite></small>
    
    <p><%= story.description %></p>
    <%= render partial: "/stories/info", locals: {story: story} %>
  </div>

</li>

app/views/stories/edit.html.erb
<% provide(:title, "Edit story") %> 
 
<h1>Update <%=@story.title%></h1>
<% if(@story.status != Story::PUBLISHED) %>
  <h2>(Private draft)</h2>
<% end %>
<%= render "graph" %>
<div class="row">
  <div class="span8 offset2">
  <h3>Details</h3>
    <%= form_for(@story) do |f| %>
      <%= render "fields", f: f %>
      <section>
      <%= f.submit "Update details", class: "btn-square btn-blue btn-square-large" %>
      </section>
    <% end %>
    
    <% if @story.status == Story::PUBLISHED %>
      <%= form_for @story, :method => :put do |f| %>
        <%= f.hidden_field :status, :value => 0 %>
        <%= f.submit "Unpublish Story", class: "btn-square btn-blue btn-square-large" %>
      <% end %>
    <% else %>
      <%= form_for @story, :method => :put do |f| %>
        <%= f.hidden_field :status, :value => 1 %>
        <%= f.hidden_field :id, :value => @story.id %>
        <%= f.submit "Publish Story", class: "btn-square btn-red btn-square-large" %>
      <% end %>
    <% end %>
        
    <div class="span9" style="margin-left:-10px">
      <h3>Pages</h3>
      <ul class="thumbnails">
        <% @story.pages.find(:all, order: "id").each do |page| %>
        <%= render partial: "pages/page", locals: { page: page } %>
        <% end %>
      </ul>
      <hr />
      <p style="display: block">
        <%= link_to "Add page", new_story_page_path(@story), method: :get, class: "btn-square btn-purple" %>&nbsp;
      
        <%= link_to "Play", story_path(@story), method: :get, class: "btn-square btn-square-large btn-green" %>
      </p>
    </div>
  </div>
  <script>
  $(window).load(function(){
    var maxHeight = 0;
    $('.thumbnails li').each(function() { maxHeight = Math.max(maxHeight, $(this).height()); }).height(maxHeight);
    
  });
  </script>
</div>

app/views/stories/graph.html.erb
<%= render "graph" %>

app/views/stories/index.html.erb

<div class="sorting_bar">
	<ul class="nav nav-pills">
	<% ["Rating","Title","Date"].each do |p| %>
		<li class="<%=p.casecmp(params[:sort]) == 0 ? "active" : "" %>">
			<%= link_to p, params.permit(:sort).merge({:sort => p.downcase}) %>
		</li>
	<% end %>
	</ul>
</div>
<div class="clearfix"></div>
<div class="pull-right">
<div id="mini_feed" class="card span3">
<h3>Recently</h3>
  <% @activity.each do |post| %>
    <%= render partial: "microposts/mini", locals: { micropost: post } %>
  <% end %>

</div>
<% if(signed_in?) %>
  <div id="new_story_button"><%= link_to "New story", new_story_path, class: "btn-square btn-blue" %></div>
<% end %>
</div>
<ul class="thumbnails span9">
  <%= render @stories %>
</ul>
<div class="clearfix"></div>
<%= will_paginate @stories %>

app/views/stories/new.html.erb
<% provide(:title, "New Story") %>
<h1>New Story</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@story) do |f| %>
      <%= render "fields", f: f %>
      <%= f.submit "Start Writing", class: "btn-square btn-blue" %>
    <% end %>
  </div>
</div>

app/views/stories/show.html.erb
<% provide(:title, @story.title) %>
 <div class="card story_box">
 <section>
    <h1><%= @story.title %></h1>
  </section>
 <div class="page_placeholder">
 <div class="page_inner popped">
  <div class="row">
    <div class="span8 offset2">
   
      <section style="text-align:center; margin-bottom:20px">
      <%= image_for_story @story, 600 %>
      </section>
      <p>
        <%= raw content_filter(@story.description) %>
      </p>  
   
    <div style="text-align:center">
    <% if !@story.first_page.nil? %>
          <%= link_to "Begin Story", story_page_path(@story, @story.first_page), class:"btn-square btn-green" %>
    <% else %>
          No pages yet!
    <% end %>
    </div>
     </div>
  </div>
  </div>
</div>
<div class="btn-round btn-round-small" id="btnMute"><i class='fa fa-volume-up'></i></div>
  <script>
    $(document).ready( function() {
      bookify($(".page_placeholder").get(0));
    });
    SCHelper.mute = false;
    $("#btnMute").click(function ()
    {
      SCHelper.mute = !SCHelper.mute;
      $(this).find("i").toggleClass( "fa fa-volume-off fa fa-volume-up");
      if(SCHelper.mute)
        SCHelper.pause();
      else
        SCHelper.play();
    });
  </script>
</div>
<%= render partial: "/shared/share_this", locals: {name: @story.title, description: @story.description } %>
<%= render partial: "audio" %>