config/routes.rb
StoryTime::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
	
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :stories do
    get 'graph'
    resources :pages do 
      resources :links
    end
    resources :normal_pages, :controller => 'pages'
    resources :end_pages, :controller => 'pages'
    resources :win_pages, :controller => 'pages'
    resources :start_pages, :controller => 'pages'
    resources :ratings
  end
  match '/stories/:story_id#:id', to: 'story#show', :via => [:get], as: 'present_story_page'
  
  match '/reports/activity', to: 'reports#recent_activity', :via => [:get]


  root to: 'stories#index'
	
	match '/', to: 'stories#index', :via => [:get]
  match '/help',    to: 'static_pages#help', :via => [:get]
  match '/about',   to: 'static_pages#about', :via => [:get]
  match '/contact', to: 'static_pages#contact', :via => [:get]

	match '/signup',  to: 'users#new', :via => [:get]
  match '/signin',  to: 'sessions#new', :via => [:get]
  match '/signout', to: 'sessions#destroy', :via => [:delete]
	
	











end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Micropost < ActiveRecord::Base

  belongs_to :user
  validates :content, presence: true, length: { maximum: 600 }
	validates :user_id, presence: true
	default_scope { order created_at: :desc }
  
  def self.get_recent(num)
    return Micropost.includes(:user).limit(num).order(id: :desc)
  end
  
  def content_without_username
    content.gsub(/^#{self.user.name} just/,'')
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
	
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Posted!"
    else
      flash[:error] = @micropost.errors.empty? ? "Post could not be created" : @micropost.errors.full_messages.to_sentence
      @feed_items = []
    end
    redirect_to :back
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Updated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
     @micropost.destroy
     redirect_to :back
  end
	
	private

    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>
      <ul>
        <% micropost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>Post something</h4>
    <%= f.text_area :content, rows: 4 %>
  </div>
    <%= f.hidden_field :user_id %>
  <div class="actions">
    <%= f.submit "Post", class: "btn-square btn-blue" %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li class="span9 card">
  <span class="content"><%= raw micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/microposts/_mini.html.erb
<div class="mini recent_activity"><small><%= link_to micropost.user.try(:name), micropost.user %> <%= time_ago_in_words(micropost.created_at) %> ago<br/><cite><%=raw micropost.content_without_username%></cite></small></div>

app/views/microposts/create.js.erb
$('#rating').replaceWith("<%= escape_javascript(render :partial => "ratings/rating") %>");

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render "form" %>

<%= link_to "Show", @micropost %> |
<%= link_to "Back", microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render "form" %>

<%= link_to "Back", microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/update.js.erb
$('#rating').replaceWith("<%= escape_javascript(render :partial => "ratings/rating") %>");