config/routes.rb
StoryTime::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
	
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :stories do
    get 'graph'
    resources :pages do 
      resources :links
    end
    resources :normal_pages, :controller => 'pages'
    resources :end_pages, :controller => 'pages'
    resources :win_pages, :controller => 'pages'
    resources :start_pages, :controller => 'pages'
    resources :ratings
  end
  match '/stories/:story_id#:id', to: 'story#show', :via => [:get], as: 'present_story_page'
  
  match '/reports/activity', to: 'reports#recent_activity', :via => [:get]


  root to: 'stories#index'
	
	match '/', to: 'stories#index', :via => [:get]
  match '/help',    to: 'static_pages#help', :via => [:get]
  match '/about',   to: 'static_pages#about', :via => [:get]
  match '/contact', to: 'static_pages#contact', :via => [:get]

	match '/signup',  to: 'users#new', :via => [:get]
  match '/signin',  to: 'sessions#new', :via => [:get]
  match '/signout', to: 'sessions#destroy', :via => [:delete]
	
	











end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :admin_user

	def recent_activity
		@activity= initialize_grid(Page,
			:order => 'created_at',
  			:order_direction => 'desc',
  			:joins => {:story => :user })
	end

	private
		
		def admin_user
      		redirect_to(root_path) unless !current_user.nil? and current_user.admin?
		end
end

app/views/reports/recent_activity.html.erb
<div class="card card-wide">
<h1>Recent Activity</h1>

<%= grid(@activity) do |g|

  g.column name: 'Created', attribute: 'created_at' do |p|
    p.created_at.strftime("%Y-%m-%d")
  end

  g.column name: 'Last Updated', attribute: 'updated_at' do |p|
    p.updated_at.strftime("%Y-%m-%d")
  end

  g.column  name: 'User', attribute: 'name', model: User do |p|
    link_to p.story.user.name, user_path(p.story.user) 
  end

  g.column  name: 'Story', attribute: 'title', model: Story do |p|
    link_to p.story.title, edit_story_path(p.story) 
  end

  g.column  name: 'Page', attribute: 'title' do |p|
    link_to p.title, edit_story_page_path(p.story, p) 
  end

  g.column name: 'Content' do |p|
    p.text
  end

  g.column name: 'Wordcount' do |p|
    p.word_count
  end
end -%>
</div>